output_paths:
  nordcap_outlet: ../../Nordcap/nordcap_outlet.csv
  nordcap_delivery_status: ../../Nordcap/nordcap_delivery_status.csv
  rivacold_delivery_status: ../../Rivacold/rivacold_delivery_status.csv
  ls_price: ../../LF/lf_price.csv
ls_price:
  auth_url: https://b2bnet.lfspareparts724.com/Login
  auth_user: AUTH_USER
  auth_password: AUTH_PASSWORD
